channels:
- pytorch
- anaconda
- conda-forge
dependencies:
- python=3.7
- pip=21.1.2
- pip:
  - azureml-core==1.42.0
  - azureml-mlflow==1.42.0
  - azureml-automl-core==1.42.0.post1
  - azureml-automl-dnn-nlp==1.42.0.post1
  - azureml-responsibleai==1.42.0
  - azureml-automl-runtime==1.42.0.post1
  - azureml-train-automl-client==1.42.0.post1
  - azureml-train-automl-runtime==1.42.0.post1
- numpy~=1.18.5
- pandas~=1.1.5
- scikit-learn~=0.22.1
- pytorch==1.7.1
name: project_environment
